
exports.up = function(knex) {
    return knex.raw(
        `
            CREATE TABLE "users" (
                user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                profile_picture text NOT NULL,
                username text NOT NULL,
                password text NOT NULL,
                points integer NOT NULL
            );

            CREATE TABLE "levels" (
                level_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                minimum_points integer NOT NULL,
                maximum_points integer NOT NULL
            );

            CREATE TABLE "level_achievements" (
                user_id integer NOT NULL,
                level_id integer NOT NULL,
                FOREIGN KEY (user_id) REFERENCES "users"(user_id),
                FOREIGN KEY (level_id) REFERENCES "levels"(level_id)
            );

            CREATE TABLE "badges" (
                badge_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                badge_name text NOT NULL,
                badge_description text NOT NULL,
                points_value integer NOT NULL
            );

            CREATE TABLE "badge_achievements" (
                user_id integer NOT NULL,
                badge_id integer NOT NULL,
                FOREIGN KEY (user_id) REFERENCES "users"(user_id),
                FOREIGN KEY (badge_id) REFERENCES "badges"(badge_id)
            );

            CREATE TABLE "groups" (
                group_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                group_name text NOT NULL,
                group_picture text NOT NULL
            );

            CREATE TABLE "group_memberships" (
                user_id integer NOT NULL,
                group_id integer NOT NULL,
                FOREIGN KEY (user_id) REFERENCES "users"(user_id),
                FOREIGN KEY (group_id) REFERENCES "groups"(group_id)
            );

            CREATE TABLE "pomodoros" (
                pomodoro_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                group_id integer NOT NULL,
                pomodoros_total integer NOT NULL,
                FOREIGN KEY (group_id) REFERENCES "groups"(group_id)
            );

            CREATE TABLE "notebooks" (
                notebook_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                group_id integer NOT NULL,
                notebook_name text NOT NULL,
                FOREIGN KEY (group_id) REFERENCES "groups"(group_id)
            );

            CREATE TABLE "notes" (
                note_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                notebook_id integer NOT NULL,
                note_content text NOT NULL,
                date_edited date NOT NULL,
                FOREIGN KEY (notebook_id) REFERENCES "notebooks"(notebook_id)
            );

            CREATE TABLE "chats" (
                chat_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                group_id integer NOT NULL,
                FOREIGN KEY (group_id) REFERENCES "groups"(group_id)
            );

            CREATE TABLE "messages" (
                message_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                chat_id integer NOT NULL,
                message_content text NOT NULL,
                date_time date NOT NULL,
                FOREIGN KEY (chat_id) REFERENCES "chats"(chat_id)
            );
        `
    );
};

exports.down = function(knex) {
    return knex.raw(
        `
        DROP TABLE 
            "users", 
            "levels",
            "level_achievements", 
            "badges", 
            "badge_achievements", 
            "groups", 
            "group_memberships", 
            "pomodoros",
            "notebooks",
            "notes",
            "chats",
            "messages"  
        ;
        `
    );
};
